// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 15 Jul 2022 11:04:22 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <stdlib.h>
#include "include/Processing.NDI.Lib.h"
#pragma once

#define __CGOGEN 1

