// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 07 Dec 2020 18:14:01 GMT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package NDI

/*
#cgo LDFLAGS: -L/usr/local/lib -lndi.4
#include <stdlib.h>
#include "include/Processing.NDI.Lib.h"
#include "cgo_helpers.h"
*/
import "C"

// FrameTypeE as declared in include/Processing.NDI.structs.h:48
type FrameTypeE int32

// FrameTypeE enumeration from include/Processing.NDI.structs.h:48
const (
	FrameTypeNone         FrameTypeE = iota
	FrameTypeVideo        FrameTypeE = 1
	FrameTypeAudio        FrameTypeE = 2
	FrameTypeMetadata     FrameTypeE = 3
	FrameTypeError        FrameTypeE = 4
	FrameTypeStatusChange FrameTypeE = 100
	FrameTypeMax          FrameTypeE = 2147483647
)

// FourCCVideoTypeE as declared in include/Processing.NDI.structs.h:120
type FourCCVideoTypeE int32

// FourCCVideoTypeE enumeration from include/Processing.NDI.structs.h:120
const (
	FourCCVideoTypeUYVY FourCCVideoTypeE = 1498831189
	FourCCTypeUYVY      FourCCVideoTypeE = 1498831189
	FourCCVideoTypeUYVA FourCCVideoTypeE = 1096178005
	FourCCTypeUYVA      FourCCVideoTypeE = 1096178005
	FourCCVideoTypeP216 FourCCVideoTypeE = 909193808
	FourCCTypeP216      FourCCVideoTypeE = 909193808
	FourCCVideoTypePA16 FourCCVideoTypeE = 909197648
	FourCCTypePA16      FourCCVideoTypeE = 909197648
	FourCCVideoTypeYV12 FourCCVideoTypeE = 842094169
	FourCCTypeYV12      FourCCVideoTypeE = 842094169
	FourCCVideoTypeI420 FourCCVideoTypeE = 808596553
	FourCCTypeI420      FourCCVideoTypeE = 808596553
	FourCCVideoTypeNV12 FourCCVideoTypeE = 842094158
	FourCCTypeNV12      FourCCVideoTypeE = 842094158
	FourCCVideoTypeBGRA FourCCVideoTypeE = 1095911234
	FourCCTypeBGRA      FourCCVideoTypeE = 1095911234
	FourCCVideoTypeBGRX FourCCVideoTypeE = 1481787202
	FourCCTypeBGRX      FourCCVideoTypeE = 1481787202
	FourCCVideoTypeRGBA FourCCVideoTypeE = 1094862674
	FourCCTypeRGBA      FourCCVideoTypeE = 1094862674
	FourCCVideoTypeRGBX FourCCVideoTypeE = 1480738642
	FourCCTypeRGBX      FourCCVideoTypeE = 1480738642
	FourCCVideoTypeMax  FourCCVideoTypeE = 2147483647
)

// FourCCAudioTypeE as declared in include/Processing.NDI.structs.h:134
type FourCCAudioTypeE int32

// FourCCAudioTypeE enumeration from include/Processing.NDI.structs.h:134
const (
	FourCCAudioTypeFLTP FourCCAudioTypeE = 1884572742
	FourCCTypeFLTP      FourCCAudioTypeE = 1884572742
	FourCCAudioTypeMax  FourCCAudioTypeE = 2147483647
)

// FrameFormatTypeE as declared in include/Processing.NDI.structs.h:150
type FrameFormatTypeE int32

// FrameFormatTypeE enumeration from include/Processing.NDI.structs.h:150
const (
	FrameFormatTypeProgressive FrameFormatTypeE = 1
	FrameFormatTypeInterleaved FrameFormatTypeE = 0
	FrameFormatTypeField0      FrameFormatTypeE = 2
	FrameFormatTypeField1      FrameFormatTypeE = 3
	FrameFormatTypeMax         FrameFormatTypeE = 2147483647
)

// RecvBandwidthE as declared in include/Processing.NDI.Recv.h:38
type RecvBandwidthE int32

// RecvBandwidthE enumeration from include/Processing.NDI.Recv.h:38
const (
	RecvBandwidthMetadataOnly RecvBandwidthE = -10
	RecvBandwidthAudioOnly    RecvBandwidthE = 10
	RecvBandwidthLowest       RecvBandwidthE = 0
	RecvBandwidthHighest      RecvBandwidthE = 100
	RecvBandwidthMax          RecvBandwidthE = 2147483647
)

// RecvColorFormatE as declared in include/Processing.NDI.Recv.h:96
type RecvColorFormatE int32

// RecvColorFormatE enumeration from include/Processing.NDI.Recv.h:96
const (
	RecvColorFormatBGRXBGRA  RecvColorFormatE = iota
	RecvColorFormatUYVYBGRA  RecvColorFormatE = 1
	RecvColorFormatRGBXRGBA  RecvColorFormatE = 2
	RecvColorFormatUYVYRGBA  RecvColorFormatE = 3
	RecvColorFormatFastest   RecvColorFormatE = 100
	RecvColorFormatBest      RecvColorFormatE = 101
	RecvColorFormatEBGRXBGRA RecvColorFormatE = 0
	RecvColorFormatEUYVYBGRA RecvColorFormatE = 1
	RecvColorFormatERGBXRGBA RecvColorFormatE = 2
	RecvColorFormatEUYVYRGBA RecvColorFormatE = 3
	RecvColorFormatMax       RecvColorFormatE = 2147483647
)
