// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 15 Jul 2022 16:14:31 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package NDI provides go bindings for the Newtek NDI SDK
*/
package ndigo
