// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 23 Jun 2022 19:13:54 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package NDI provides go bindings for the Newtek NDI SDK
*/
package ndigo
